/**
 * Feature manifest imports — importing this module registers every feature.
 * Add new features here and nowhere else.
 */
import '@/features/units'
import '@/features/interface'
import '@/features/search'
import '@/features/graticule'
import '@/features/radar'
import '@/features/radar/level2'
import '@/features/wind'
import '@/features/fields'
import '@/features/fronts'
import '@/features/satellite'
import '@/features/lightning'
import '@/features/metar'
import '@/features/aviation'
import '@/features/gauges'
import '@/features/buoys'
import '@/features/alerts'
import '@/features/spc'
import '@/features/cells'
import '@/features/conditions'
import '@/features/forecast'
import '@/features/notify'
import '@/features/meteogram'
import '@/features/sounding'
import '@/features/models'
