/**
 * The data catalog: every upstream dataset, API-documentation style — what
 * we call, with which parameters, at what cadence, and what capability the
 * source offers that we don't use yet. Pure data; DataPage renders it.
 * All sources are free and keyless (the project's standing constraint).
 */

export type Assessment = 'best available' | 'upgrade candidate' | 'adequate'

export interface Dataset {
  id: string
  name: string
  provider: string
  href: string
  /** How the bytes reach the client. */
  transport: string
  endpoint: string
  /** Parameters we actually send, name → value/meaning. */
  params: Array<{ name: string; value: string }>
  cadence: string
  latency: string
  resolution: string
  coverage: string
  /** App features consuming it. */
  usedBy: string[]
  /** User-facing settings that change what we request or show. */
  settings: string[]
  /** Capability the source offers that we do not use yet. */
  unused: string[]
  assessment: Assessment
  note: string
}

export const DATA_CATALOG: Dataset[] = [
  {
    id: 'iem-nexrad-mosaic',
    name: 'NEXRAD composite mosaic (N0Q)',
    provider: 'Iowa Environmental Mesonet',
    href: 'https://mesonet.agron.iastate.edu/ogc/',
    transport: 'WMS tiles, recoloured in-browser to our dBZ palette',
    endpoint: 'mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0q-t.cgi',
    params: [
      { name: 'TIME', value: 'ISO timestamp, 5-min steps — pins every zoom to one generation' },
      { name: 'BBOX', value: '{bbox-epsg-3857}, per tile' },
    ],
    cadence: '5 min',
    latency: '~5 min',
    resolution: '~1 km',
    coverage: 'CONUS + fringes',
    usedBy: ['radar (mosaic source)', 'radar loop + prefetch'],
    settings: ['Radar source', 'loop speed', 'opacity'],
    unused: ['N0R 4-bit product', 'single-site RIDGE tiles', 'precip type mosaics (ptype)'],
    assessment: 'upgrade candidate',
    note: 'The canonical free mosaic, but MRMS (2-min, quality-controlled, multi-sensor) exists on the same IEM WMS infrastructure and is the modern standard composite.',
  },
  {
    id: 'iem-archive',
    name: 'NEXRAD mosaic archive',
    provider: 'Iowa Environmental Mesonet',
    href: 'https://mesonet.agron.iastate.edu/docs/nexrad_mosaic/',
    transport: 'PNG world-files',
    endpoint: 'mesonet.agron.iastate.edu/archive/data/…/GIS/uscomp/n0q_YYYYMMDDHHMI.png',
    params: [{ name: 'path', value: 'timestamped path, 5-min granularity' }],
    cadence: '5 min',
    latency: 'archive (minutes behind live)',
    resolution: '~1 km',
    coverage: 'CONUS',
    usedBy: ['historic radar scrubbing'],
    settings: ['timeline position'],
    unused: ['pre-2011 archive depth', 'Alaska/Hawaii/PR composites'],
    assessment: 'best available',
    note: 'Only keyless multi-year radar archive with stable URLs.',
  },
  {
    id: 'rainviewer',
    name: 'Global precipitation composite',
    provider: 'RainViewer',
    href: 'https://www.rainviewer.com/api.html',
    transport: 'JSON frame index → XYZ tiles',
    endpoint: 'api.rainviewer.com/public/weather-maps.json',
    params: [
      { name: 'frame path', value: 'from the index; colour scheme + smoothing baked into path' },
    ],
    cadence: '10 min',
    latency: '~10 min',
    resolution: '~2 km (varies by contributing radar)',
    coverage: 'Global (where radars exist)',
    usedBy: ['radar (worldwide source)'],
    settings: ['Radar source'],
    unused: ['30-min nowcast frames', 'infrared satellite composite layer'],
    assessment: 'adequate',
    note: 'Best keyless global composite. Palette differs from our mosaic dBZ palette — a known visual mismatch between radar sources. Nowcast frames are the hook for predicted-radar looping.',
  },
  {
    id: 'nexrad-level2',
    name: 'NEXRAD Level 2 real-time volumes',
    provider: 'NOAA / Unidata on AWS Open Data',
    href: 'https://registry.opendata.aws/noaa-nexrad/',
    transport: 'S3 chunk listing + GRIB-like volumes, decoded in-browser (proxied: bucket blocks CORS)',
    endpoint: '/proxy/nexrad → unidata-nexrad-level2-chunks.s3.amazonaws.com',
    params: [
      { name: 'list-type', value: 'listing polls (never cached)' },
      { name: 'chunk key', value: 'site/volume/chunk (immutable, cached 1 h)' },
    ],
    cadence: 'chunks stream every few seconds; full volume 4–6 min',
    latency: 'seconds',
    resolution: 'super-res: 0.25 km × 0.5°',
    coverage: 'Per-site, CONUS + territories',
    usedBy: ['radar Level 2 (single-site)', 'radar workbench tools'],
    settings: ['site pick', 'elevation/product in workbench'],
    unused: ['dual-pol moments beyond current products', 'the full historical archive bucket'],
    assessment: 'best available',
    note: 'This is the raw instrument. Nothing fresher or finer exists, free or paid.',
  },
  {
    id: 'iem-nexrad-attr',
    name: 'NEXRAD storm attributes',
    provider: 'Iowa Environmental Mesonet',
    href: 'https://mesonet.agron.iastate.edu/request/gis/nexrad_storm_attrs.php',
    transport: 'GeoJSON',
    endpoint: 'mesonet.agron.iastate.edu/geojson/nexrad_attr.geojson',
    params: [{ name: '(none)', value: 'full national set each poll' }],
    cadence: 'per volume scan (~5 min)',
    latency: 'minutes',
    resolution: 'cell-level points',
    coverage: 'CONUS',
    usedBy: ['cells (TVS / meso / hail icons + motion vectors)'],
    settings: ['cells layer toggle'],
    unused: ['attribute history for track reconstruction'],
    assessment: 'best available',
    note: 'The radar-derived cell table the NWS itself uses; no richer keyless feed exists.',
  },
  {
    id: 'nws-alerts',
    name: 'Watches / warnings / advisories',
    provider: 'National Weather Service API',
    href: 'https://www.weather.gov/documentation/services-web-api',
    transport: 'GeoJSON (CAP)',
    endpoint: 'api.weather.gov/alerts/active?status=actual',
    params: [{ name: 'status', value: 'actual — no test/exercise messages' }],
    cadence: 'poll ~1 min',
    latency: 'seconds from issuance',
    resolution: 'polygon / zone',
    coverage: 'US + coastal waters',
    usedBy: ['alerts layer', 'notify rules', 'home-alerts summary'],
    settings: ['notification severity floor', 'alert filters'],
    unused: ['zone/county geometry service', 'marine zones', 'alert history endpoint'],
    assessment: 'best available',
    note: 'The authoritative source, straight from the issuing agency.',
  },
  {
    id: 'open-meteo-forecast',
    name: 'Deterministic forecasts (multi-model)',
    provider: 'Open-Meteo',
    href: 'https://open-meteo.com/en/docs',
    transport: 'JSON',
    endpoint: 'api.open-meteo.com/v1/forecast',
    params: [
      { name: 'hourly / current / daily', value: 'temperature, precip, wind, cloud, pressure…' },
      { name: 'models', value: 'gfs, ecmwf_ifs025, icon, gem, ukmo (seamless blends)' },
      { name: 'forecast_days / past_days', value: 'up to 16 ahead, 1 back' },
    ],
    cadence: 'model cycles (1–6 h)',
    latency: 'hours (model production time)',
    resolution: '1–11 km depending on model',
    coverage: 'Global',
    usedBy: ['conditions (Now)', 'forecast panels + verdict', 'meteogram', 'models comparison'],
    settings: ['units', 'model selection in comparison'],
    unused: [
      '15-minutely variables',
      'solar/radiation fields',
      'ECMWF AIFS (the ML model) as a comparison member',
      'historical reanalysis API',
    ],
    assessment: 'best available',
    note: 'The best keyless multi-model aggregator there is. AIFS would be a free upgrade to the model-agreement panel.',
  },
  {
    id: 'open-meteo-ensemble',
    name: 'Ensemble forecasts',
    provider: 'Open-Meteo',
    href: 'https://open-meteo.com/en/docs/ensemble-api',
    transport: 'JSON',
    endpoint: 'ensemble-api.open-meteo.com/v1/ensemble',
    params: [{ name: 'hourly + models', value: 'per-member series for spread displays' }],
    cadence: 'model cycles',
    latency: 'hours',
    resolution: 'member grids (coarser than deterministic)',
    coverage: 'Global',
    usedBy: ['forecast uncertainty bands', 'model confidence'],
    settings: ['units'],
    unused: ['more ensemble systems than we chart'],
    assessment: 'best available',
    note: 'Free per-member ensemble data is otherwise nearly unobtainable.',
  },
  {
    id: 'open-meteo-sounding',
    name: 'Model vertical profiles',
    provider: 'Open-Meteo',
    href: 'https://open-meteo.com/en/docs',
    transport: 'JSON (19 pressure levels)',
    endpoint: 'api.open-meteo.com/v1/forecast (pressure-level variables)',
    params: [
      { name: 'hourly', value: 'T, RH, wind, geopotential at 1000→30 hPa' },
      { name: 'wind_speed_unit', value: 'ms' },
    ],
    cadence: 'model cycles',
    latency: 'hours',
    resolution: 'model column at point',
    coverage: 'Global',
    usedBy: ['sounding (skew-T, hodograph, indices)'],
    settings: ['probe point', 'timeline hour'],
    unused: ['more levels via specific models', 'cloud water profiles'],
    assessment: 'best available',
    note: 'Model profile; the observed-balloon overlay covers the truth side.',
  },
  {
    id: 'open-meteo-aq',
    name: 'Air quality',
    provider: 'Open-Meteo (CAMS)',
    href: 'https://open-meteo.com/en/docs/air-quality-api',
    transport: 'JSON',
    endpoint: 'air-quality-api.open-meteo.com/v1/air-quality',
    params: [{ name: 'hourly', value: 'us_aqi, pm2_5' }],
    cadence: 'hourly',
    latency: '~hours (CAMS production)',
    resolution: '~11 km (CAMS global)',
    coverage: 'Global',
    usedBy: ['conditions (Now panel AQI row)'],
    settings: ['probe point'],
    unused: ['pollen (Europe)', 'per-pollutant AQI breakdown', 'a map layer'],
    assessment: 'adequate',
    note: 'Model AQ, not station obs. AirNow has US station truth but requires a key.',
  },
  {
    id: 'open-meteo-geocoding',
    name: 'Location search',
    provider: 'Open-Meteo',
    href: 'https://open-meteo.com/en/docs/geocoding-api',
    transport: 'JSON',
    endpoint: 'geocoding-api.open-meteo.com/v1/search',
    params: [{ name: 'name', value: 'query string' }],
    cadence: 'on demand',
    latency: 'instant',
    resolution: 'place',
    coverage: 'Global',
    usedBy: ['search (Ctrl+K)'],
    settings: [],
    unused: ['reverse geocoding'],
    assessment: 'adequate',
    note: 'Does the job; Nominatim is the keyless alternative if it ever falls short.',
  },
  {
    id: 'gibs',
    name: 'Satellite imagery',
    provider: 'NASA GIBS',
    href: 'https://nasa-gibs.github.io/gibs-api-docs/',
    transport: 'WMTS XYZ tiles (z/y/x)',
    endpoint: 'gibs.earthdata.nasa.gov/wmts/epsg3857/best/{product}/default/{time}/…',
    params: [
      { name: 'product', value: 'GeoColor, Band13 IR, Band2 visible, Air Mass (GOES-East); VIIRS true color + IR (daily)' },
      { name: 'time', value: 'ISO timestamp snapped to product cadence, clamped behind measured lag' },
    ],
    cadence: '10 min (GOES) / daily (VIIRS)',
    latency: '35–55 min (measured)',
    resolution: '1–2 km at best zoom',
    coverage: 'Western hemisphere (GOES-East) / global (VIIRS)',
    usedBy: ['satellite layer'],
    settings: ['product', 'opacity'],
    unused: ['GOES-West layers', 'hundreds of science layers', 'no GOES water-vapour band exists here — Air Mass is the WV-derived substitute'],
    assessment: 'upgrade candidate',
    note: 'Rock-solid and keyless, but the ~45-min lag is why clouds freeze in the live radar loop. SSEC RealEarth serves GOES tiles minutes-fresh (key-gated but free) — the candidate fix.',
  },
  {
    id: 'blitzortung',
    name: 'Lightning strikes',
    provider: 'Blitzortung.org community network',
    href: 'https://www.blitzortung.org/',
    transport: 'WebSocket stream (LZW-coded)',
    endpoint: 'wss://ws1/ws7/ws8.blitzortung.org',
    params: [{ name: '(subscription)', value: 'global stream, client-side windowing' }],
    cadence: 'continuous',
    latency: 'seconds',
    resolution: 'strike points (~km accuracy)',
    coverage: 'Global (density follows detector coverage)',
    usedBy: ['lightning layer (age-faded bolts)'],
    settings: ['fade minutes'],
    unused: ['strike polarity/current where present'],
    assessment: 'best available',
    note: 'Only keyless real-time lightning stream in existence. GOES GLM gridded products lag and lack point detail.',
  },
  {
    id: 'awc-metar',
    name: 'Surface observations (METAR)',
    provider: 'Aviation Weather Center data API',
    href: 'https://aviationweather.gov/data/api/',
    transport: 'JSON (proxied: origin blocks browsers)',
    endpoint: '/proxy/metar → aviationweather.gov/api/data/metar',
    params: [
      { name: 'bbox', value: 'viewport-quantized; wide national box at chart zooms' },
      { name: 'format', value: 'json' },
    ],
    cadence: 'obs hourly + specials; poll 5 min',
    latency: 'minutes',
    resolution: 'station',
    coverage: 'Global (dense in NA/EU)',
    usedBy: ['metar station plots', 'surface chart carpet'],
    settings: ['station density (sparse/normal/dense)'],
    unused: ['visibility/ceiling → flight-category colouring (queued)', 'cloud layer groups', 'raw ob text'],
    assessment: 'best available',
    note: 'The cleanest keyless METAR JSON. Flight-category colouring is on the polish list.',
  },
  {
    id: 'awc-hazards',
    name: 'SIGMETs and PIREPs',
    provider: 'Aviation Weather Center data API',
    href: 'https://aviationweather.gov/data/api/',
    transport: 'JSON (proxied)',
    endpoint: '/proxy/awc/airsigmet · /proxy/awc/pirep',
    params: [
      { name: 'type', value: 'sigmet (without it the endpoint returns AIRMETs)' },
      { name: 'age / bbox', value: 'PIREPs: 2 h history, viewport box' },
    ],
    cadence: 'as issued; poll 5 min',
    latency: 'minutes',
    resolution: 'polygon / point report',
    coverage: 'US FIRs + international SIGMETs',
    usedBy: ['aviation layer + panel'],
    settings: ['sigmets on/off', 'pireps on/off'],
    unused: ['TAFs', 'G-AIRMETs (LINE geometries)', 'CWAs', 'station info service'],
    assessment: 'best available',
    note: 'Canonical source. TAF/G-AIRMET are deferred slices, not data gaps.',
  },
  {
    id: 'nomads-gfs',
    name: 'GFS gridded fields',
    provider: 'NOAA NOMADS (filter CGI)',
    href: 'https://nomads.ncep.noaa.gov/',
    transport: 'GRIB2 → decoded server-side → quantized binary (uint16 + header)',
    endpoint: '/proxy/gfs-wind?level= · /proxy/gfs-grid?field=',
    params: [
      { name: 'wind', value: 'UGRD/VGRD at 10 m, 850, 700, 500 hPa' },
      { name: 'fields', value: 'MSLET (membrane MSLP), HGT 500, TMP 850, CAPE surface' },
      { name: 'hour', value: 'f000 analysis of the latest cycle only' },
    ],
    cadence: '4 cycles/day',
    latency: '~3.5–5 h after cycle time',
    resolution: '0.25° source, decimated to 0.5° on our server',
    coverage: 'Global',
    usedBy: ['wind particles', 'fields (isobars/heights/temp/CAPE)', 'surface chart centres'],
    settings: ['wind level + particles', 'field + isobar interval + opacity'],
    unused: [
      'forecast hours f003–f384 (future scrubbing)',
      'full 0.25° resolution',
      'hundreds of other variables/levels',
      'GEFS ensemble grids on the same host',
    ],
    assessment: 'upgrade candidate',
    note: 'Right source, partially used: forecast-hour stepping and full resolution are feature work waiting on the same endpoint. MSLET replaced PRMSL after the terrain-noise war.',
  },
  {
    id: 'wpc-codsus',
    name: 'Surface analysis fronts',
    provider: 'WPC via IEM AFOS archive',
    href: 'https://www.wpc.ncep.noaa.gov/html/sfc2.shtml',
    transport: 'coded text bulletin (ASUS02 KWBC), parsed in-browser',
    endpoint: 'mesonet.agron.iastate.edu/cgi-bin/afos/retrieve.py?pil=CODSUS',
    params: [{ name: 'pil', value: 'CODSUS — the machine-readable Unified Surface Analysis' }],
    cadence: '~3-hourly',
    latency: 'minutes after issuance',
    resolution: 'analyst front/trough vertices (~0.1°)',
    coverage: 'North America and adjacent oceans',
    usedBy: ['fronts layer (pips, troughs)'],
    settings: [],
    unused: [
      'the H/L centre list (deliberately: they sit on an unpublished pressure grid and float ringless over ours)',
      'AFOS archive depth for historic fronts',
    ],
    assessment: 'best available',
    note: "The only machine-readable form of the analysts' fronts. WPC's isobar grid itself is never published.",
  },
  {
    id: 'spc',
    name: 'Convective outlooks, watches, MCDs',
    provider: 'Storm Prediction Center (+ IEM helpers)',
    href: 'https://www.spc.noaa.gov/',
    transport: 'GeoJSON',
    endpoint:
      'spc.noaa.gov/products/outlook/day{1-3}otlk_cat.lyr.geojson · IEM spcwatch.py · IEM spc_mcd.geojson',
    params: [
      { name: 'day', value: '1–3 categorical' },
      { name: '(watches)', value: 'active only — expired vanish from the feed' },
    ],
    cadence: 'outlooks on schedule; watches/MCDs as issued (poll 5 min)',
    latency: 'minutes',
    resolution: 'forecast polygons',
    coverage: 'CONUS',
    usedBy: ['spc layer + panel (watch details, MCD text)'],
    settings: ['outlook day', 'watches', 'MCDs'],
    unused: ['probabilistic tornado/wind/hail outlooks', 'Day 4–8', 'fire weather outlooks', 'storm reports (LSRs)'],
    assessment: 'best available',
    note: 'Official colours ride in the .lyr files. Storm reports are the obvious next pull.',
  },
  {
    id: 'iem-raob',
    name: 'Observed balloon soundings',
    provider: 'Iowa Environmental Mesonet RAOB archive',
    href: 'https://mesonet.agron.iastate.edu/archive/raob/',
    transport: 'JSON',
    endpoint: 'mesonet.agron.iastate.edu/json/raob.py?ts=&station=',
    params: [
      { name: 'ts', value: 'YYYYMMDDHHMM at 00Z/12Z, one-cycle fallback for missed launches' },
      { name: 'station', value: 'nearest online site within 400 km (network list, area aliases skipped)' },
    ],
    cadence: '12 h (00Z / 12Z launches)',
    latency: '~2 h archive lag',
    resolution: 'significant + mandatory levels',
    coverage: 'North America network (global archive exists)',
    usedBy: ['sounding observed overlay (dashed on the skew-T)'],
    settings: ['observed overlay toggle'],
    unused: ['observed-parcel indices', 'hodograph overlay', 'special 06/18Z launches'],
    assessment: 'best available',
    note: 'Same archive the analysis tools use, open CORS, no proxy needed.',
  },
  {
    id: 'nwps',
    name: 'River gauges + flood categories',
    provider: 'NWS National Water Prediction Service',
    href: 'https://api.water.noaa.gov/nwps/v1/docs/',
    transport: 'JSON',
    endpoint: 'api.water.noaa.gov/nwps/v1/gauges',
    params: [
      { name: 'bbox.*', value: 'viewport-quantized box' },
      { name: 'srid', value: 'EPSG_4326 — mandatory, silently empty without it' },
    ],
    cadence: 'gauge obs ~15 min; poll 15 min',
    latency: 'minutes–hour',
    resolution: 'gauge points',
    coverage: 'US',
    usedBy: ['gauges layer (AHPS colours, flooding-only filter)'],
    settings: ['flooding only'],
    unused: ['stage/flow time series per gauge', 'forecast crests', 'flood inundation maps'],
    assessment: 'best available',
    note: 'Replaced the planned USGS IV feed because it carries flood categories. Forecast crests are the click-through slice.',
  },
  {
    id: 'ndbc',
    name: 'Marine buoy observations',
    provider: 'NDBC',
    href: 'https://www.ndbc.noaa.gov/',
    transport: 'fixed-width text → parsed to JSON by our proxy (no CORS upstream)',
    endpoint: '/proxy/ndbc → ndbc.noaa.gov/data/latest_obs/latest_obs.txt',
    params: [{ name: '(none)', value: 'one global file, every station' }],
    cadence: '10 min–hourly by station; proxy caches 10 min',
    latency: 'minutes',
    resolution: 'station',
    coverage: 'Global moored buoys + coastal stations',
    usedBy: ['buoys layer (wave-height colours + labels)'],
    settings: ['units (m/ft labels)'],
    unused: ['spectral wave data', 'per-station history files', 'tide stations'],
    assessment: 'best available',
    note: 'The canonical real-time marine obs file. A WaveWatch III model field from NOMADS is the missing companion layer.',
  },
  {
    id: 'openfreemap',
    name: 'Basemap',
    provider: 'OpenFreeMap · OpenMapTiles · OpenStreetMap',
    href: 'https://openfreemap.org/',
    transport: 'vector tiles',
    endpoint: 'tiles.openfreemap.org',
    params: [{ name: 'style', value: 'customized dark/light chart styles' }],
    cadence: 'periodic OSM refresh',
    latency: 'n/a',
    resolution: 'vector',
    coverage: 'Global',
    usedBy: ['the map itself'],
    settings: ['colour scheme'],
    unused: ['3D building data'],
    assessment: 'best available',
    note: 'Keyless vector basemap with no usage caps; the reason the app needs no map token.',
  },
]
